global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]

  - job_name: 'backend'
    static_configs:
      - targets: [ 'backend:8000' ]
    metrics_path: '/metrics'